# Generated by Django 5.0.1 on 2024-02-07 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('race', models.CharField(choices=[('human', 'Human'), ('skaven', 'Skaven'), ('greenskins', 'Greenskins'), ('high_elves', 'High Elves'), ('chaos_undivided', 'Chaos Undivided')], max_length=100)),
                ('faction', models.CharField(choices=[('human', [('empire', 'Empire'), ('brettonia', 'Brettonia'), ('golden_order', 'Golden Order'), ('huntsmarshal', "The Huntsmarshal's Expedition")]), ('skaven', [('clan_skryre', 'Clan Skryre'), ('clan_eshin', 'Clan Eshin')]), ('greenskins', [('grimgor', "Grimgor's Ardboyz"), ('broken_axe', 'Broken Axe')]), ('high_elves', [('eataine', 'Eataine'), ('avelorn', 'Avelorn'), ('yvresse', 'Yvresse')]), ('chaos_undivided', [('legion_of_chaos', 'Legion of Chaos'), ('shadow_legion', 'Shadow Legion')])], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='figurines')),
                ('dimensions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop.dimensions')),
            ],
        ),
    ]
