# Generated by Django 5.0.2 on 2024-02-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_figure_dimensions_figure_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='price',
            new_name='price_usd',
        ),
    ]
